# React
FROM node:latest AS builder
WORKDIR /app

ARG REACT_APP_AUTH0_DOMAIN
ARG REACT_APP_AUTH0_CLIENT_ID
ARG REACT_APP_AUTH0_CALLBACK_URL
ARG REACT_APP_FIREBASE_API_KEY
ARG REACT_APP_FIREBASE_AUTH_DOMAIN
ARG REACT_APP_FIREBASE_PROJECT_ID
ARG REACT_APP_FIREBASE_STORAGE_BUCKET
ARG REACT_APP_FIREBASE_MESSAGING_SENDER_ID
ARG REACT_APP_FIREBASE_APP_ID
ARG REACT_APP_FIREBASE_MEASUREMENT_ID
ARG REACT_APP_API_BASE_URL

ENV REACT_APP_AUTH0_DOMAIN=$REACT_APP_AUTH0_DOMAIN \ 
    REACT_APP_AUTH0_CLIENT_ID=$REACT_APP_AUTH0_CLIENT_ID \ 
    REACT_APP_AUTH0_CALLBACK_URL=$REACT_APP_AUTH0_CALLBACK_URL \ 
    REACT_APP_FIREBASE_API_KEY=$REACT_APP_FIREBASE_API_KEY \ 
    REACT_APP_FIREBASE_AUTH_DOMAIN=$REACT_APP_FIREBASE_AUTH_DOMAIN \ 
    REACT_APP_FIREBASE_PROJECT_ID=$REACT_APP_FIREBASE_PROJECT_ID \ 
    REACT_APP_FIREBASE_STORAGE_BUCKET=$REACT_APP_FIREBASE_STORAGE_BUCKET \ 
    REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$REACT_APP_FIREBASE_MESSAGING_SENDER_ID \ 
    REACT_APP_FIREBASE_APP_ID=$REACT_APP_FIREBASE_APP_ID \ 
    REACT_APP_FIREBASE_MEASUREMENT_ID=$REACT_APP_FIREBASE_MEASUREMENT_ID \ 
    REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL 

COPY package*.json ./
RUN npm install
COPY . .

ENV NODE_OPTIONS="--max-old-space-size=1024"

RUN npm run build

# Nginx
FROM alpine
WORKDIR /var/www/frontend
COPY --from=builder /app/build .
CMD ["sh", "-c", "echo 'Static files are ready in volume'"]